### PR TITLE
Use google.inject annotations instead of javax

### PR DESCRIPTION
**Pull request by wendigo**
Follow up to the https://github.com/airlift/airlift/pull/1067 as discussed with @electrum

### CODE REVIEW

**Comment by wendigo** [comment]
cc @electrum @findepi

**Comment by wendigo** [comment]
I'd like to switch Trino to google.inject as well. We've discussed it with @electrum that it'd make switch to guice 7.0 easier (it is jakarta based).

**Comment by findepi** [comment]
does this mean that Guice 7 no longer honors `javax.inject.Inject` annotations?

**Comment by wendigo** [comment]
@findepi yes, it has moved to jakarta.* namespace. Hence this change.

**Comment by wendigo** [comment]
ping @electrum @martint

**Pull request merged**
