### PR TITLE
Seal BodyGenerator - disallow custom implementations

### LINKED ISSUE #1181: Seal BodyGenerator
We should probably seal the interface, as a separate change.

_Originally posted by @electrum in https://github.com/airlift/airlift/pull/1172#discussion_r1626412524_

### PR DESCRIPTION
**Pull request by Randgalt**
Closes #1181

### CODE REVIEW

**Review by electrum — APPROVED** [review]
We can also remove the deprecated `write()` method

**Review by Randgalt — COMMENTED** [review]
@electrum I just added a commit that introduces a new `JettyBodyGenerator` to allow custom body generators. wdyt?

**Comment by electrum** [comment]
I don't think we want that. The Airlift API is intended to be independent of Jetty. The Jetty content API doesn't seem like something you would want to implement directly, so if there is a use case, let's figure out an appropriate API.

**Comment by electrum** [comment]
Why would we need that after #1172?

**Comment by Randgalt** [comment]
> We can also remove the deprecated `write()` method

@electrum we need a solution for `JaxrsTestingHttpProcessor.getRequestBody()`. We could add a similar switch on `BodyGenerator` but that feels wrong. Maybe we remove `JaxrsTestingHttpProcessor`. What is it used for?

**Comment by electrum** [comment]
Hmm. It's used to allow direct testing of a JAX-RS resource via `TestingHttpClient`. It's used in one place in Trino. Since this is part of Airlift and it's for testing, having knowledge of the body generators seems fine. Simply supporting `StaticBodyGenerator` is probably sufficient.

**Pull request merged**
