### PR TITLE
Increase default HTTP client selector count

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
A larger number of selectors will help HTTP clients serve more traffic
by default.

### CODE REVIEW

**Comment by electrum** [comment]
What are the downsides to doing this? Does it increase resource usage?

**Comment by nezihyigitbasi** [comment]
Presto test here: https://github.com/prestodb/presto/pull/10743

**Comment by nezihyigitbasi** [comment]
Presto tests look good.

**Comment by nezihyigitbasi** [comment]
Will set this config elsewhere as discussed offline.

**Pull request closed without merging**
