### PR TITLE
Fix ignoring trailing content in JsonCodec

### PR DESCRIPTION
**Pull request by findepi**
Follow-up to https://github.com/trinodb/trino/pull/12907, https://github.com/trinodb/trino/pull/12862 and https://github.com/trinodb/trino/pull/10783

### CODE REVIEW

**Review by electrum — COMMENTED** [review]
The tests don’t seem to match the code. How come the message you added doesn’t appear in the exception?

**Comment by findepi** [comment]
rebased to resolve conflict in CHANGES

PTAL

**Comment by findepi** [comment]
rebased, PTAL

**Review by martint — APPROVED** [review]

**Comment by findepi** [comment]
*rebased to resolve conflicts, no other changes)

**Comment by findepi** [comment]
thanks @martint for review

**Pull request merged**
