### PR TITLE
Update to Jetty 9.3.11.M0

### PR DESCRIPTION
**Pull request by cberner**
This fixes a race when using async responses

### CODE REVIEW

**Comment by martint** [comment]
looks good

**Comment by electrum** [comment]
This should be done in airbase.

**Comment by cberner** [comment]
I think it's better to have it in the airlift pom. Putting them in airbase is error prone, as it's less obvious what version is being used. imo, we should remove Jetty from airbase entirely

**Comment by electrum** [comment]
I'm fine with removing it, but don't just update it here, because any projects using airbase will pull the wrong version.

**Pull request merged**
