### PR TITLE
Add TOML configuration support

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by wendigo** [comment]
I wanted to keep it simple so instead of introducing new abstractions - TOML files are read and converted to Map<String, String> for consistency with .properties loading

**Comment by martint** [comment]
Nice! I've been wanting to look at what it it would take to support TOML for configuration in Airlift.

I do think, however, that we need to explore how TOML types and general structure map into Airlift configs more carefully. The approach of interpreting everything as strings may make cause incompatibilities once we do proper and idiomatic mappings.

**Comment by wendigo** [comment]
@martint we could replace coercion that we have right now in ConfigurationFactory with an explicit typed get

**Comment by wendigo** [comment]
@martint i've added support for injecting lists and maps recently so we can leverage that. We could easily add configuration class nesting

**Pull request closed without merging**
