### PR TITLE
Notify AsyncContext on remote exception

### PR DESCRIPTION
**Pull request by wendigo**
https://github.com/jetty/jetty.project/pull/11897

### CODE REVIEW

**Review by findepi — COMMENTED** [review]
cc @losipiuk 

is this testable?

**Comment by wendigo** [comment]
@findepi hardly :(

**Comment by wendigo** [comment]
Right now this is unguarded by the Jetty's config property (so on by default) but since this is going to be fixed we need to set this config explicitly.

**Review by findepi — APPROVED** [review]
code lgtm. it would be awesome to have a test.
i don't understand the limitation here

**Pull request merged**
