### PR TITLE
Add RetryDriver

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by kokosing** [comment]
@findepi @electrum Would you like to take a look?

**Comment by kokosing** [comment]
More or less it is a copy of `RetryDriver` from `presto-hive` connector with changes from #713.

**Comment by kokosing** [comment]
@electrum @dain ping

**Comment by electrum** [comment]
I don’t think we want to add this as a generic library. The code is messy and the API is not great, especially around exception handing. We probably want some Guice and configuration integration as well.

I’d prefer to look at existing alternatives such as https://github.com/jhalterman/failsafe

For the HTTP client, let’s have a private copy of the code for now. Exposing a public library with a good, stable API is a lot of work.

(This is my opinion. Others may disagree.)

**Comment by kokosing** [comment]
Thanks for your opinion. That would mean that we could (should?) migrate `RetryDriver` in Presto to something else (like `failsafe` you mentioned).

**Comment by electrum** [comment]
I just played around with `failsafe` and took a quick look through the code, and I'm impressed, it looks quite nice. I think it could easily replace `RetryDriver` (though I don't know if it's worth doing so).

**Pull request closed without merging**
