### PR TITLE
Use `Objects.deepEquals` to address array type parameters

### PR DESCRIPTION
**Pull request by reugn**

### CODE REVIEW

**Comment by findepi** [comment]
I'd rather discourage array as config values. Why not use List instead?

**Comment by reugn** [comment]
Application specifics. I could use a List but then would need to convert the value twice. There are several examples of built-in array support in the configuration, for instance, the Spring framework. Why not supporting that?

**Comment by findepi** [comment]
Arrays are mutable. While Config objects are by nature mutable too, it's recommended that config values are immutable. Otherwise using code needs to make defensive copy anyway, which doesn't avoid "convert the value twice" concern.

**Comment by reugn** [comment]
That makes sense. If you think that supporting arrays in assertions will harm the framework, please close this PR.

**Pull request merged**
