### PR TITLE
Use latest Java8 in Travis

### PR DESCRIPTION
**Pull request by dain**

### CODE REVIEW

**Comment by martint** [comment]
looks good

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious, Maven dependency caching was available since December 17, 2014, but I see you just enabled it in this pull request (about a year later). Any reasons, please? 

Thanks.

**Comment by findepi** [comment]
@Taher-Ghaleb  We moved to GitHub Actions here.

**Comment by Taher-Ghaleb** [comment]
I see. Thanks, @findepi.

**Pull request merged**
