### PR TITLE
[launcher.py] Respect JAVA_HOME

### PR DESCRIPTION
**Pull request by bdw**
Ensure that the `JAVA_HOME` environment variable, if set, is respected; this helps users (like myself) who have multiple JDK variants installed

### CODE REVIEW

**Comment by electrum** [comment]
Thanks for PR. However, I’m not sure we want this change.

We tell users to put the desired JDK first in `PATH`. Using `JAVA_HOME` would be a behavior change and could break people relying on the current behavior.

Does changing `PATH` work for you?

**Comment by bdw** [comment]
In many operating systems (in particular, in fedora, but I think also debian) the `java` executable in the `PATH` is really a symlink to something installed elsewhere, `/usr/lib/jvm/java-11-openjdk-11.0.10.0.9-0.fc33.x86_64/bin/java` - and it is also common to have an application which runs on a particular version of the JDK (say, 8), and another that runs on JDK11, or JDK14, or whatever. `JAVA_HOME` is a easy and commonly supported way to override the path to the java executable; far less invasive than updating `PATH`.

Matter of fact quite a few systems have the opposite 'problem' - they won't work without setting `JAVA_HOME` :smile: 

Unfortunately write once run everywhere didn't really work out, otherwise we wouldn't be having this discussion.

The way I see it - respecting that you may see this differently - this add a feature that is fairly commonly expected of java services and doesn't affect anybody who doesn't care or doesn't know about it.

**Comment by findepi** [comment]
What i've seen OS-es doing is to put `java` executable on `PATH`, which is not a dumb wrapper. Instead this "`$PATH/java`"  would inspect `JAVA_HOME` env (if set), and forward appropriately.
Obviously this isn't the case in your case, otherwise you wouldn't want this change here.

**Comment by electrum** [comment]
This would be a breaking change if people are relying on the current `PATH` behavior but also have `JAVA_HOME` set to a location that is inconsistent with `PATH`. I'm hesitant to make this change, even if this scenario seems uncommon or unlikely, since the launcher is invoked from various places, and this sort of breakage might not be obvious when upgrading.

Would it make sense to enable this using a config flag for the launcher? Or does this scenario seem so unlikely as to not be worth considering?

**Comment by bdw** [comment]
Yeah, it's true that this could be breaking in some edge cases.

Then again, could be *your* edge case, in which case, you'd probably rather not have a production outage.

It's unfortunate but I think I'll close this ticket then.

**Comment by pan3793** [comment]
It's rare that a Java software silently ignores the `JAVA_HOME`, I suppose usually that `JAVA_HOME` takes higher priority than `java` under `PATH`, is it possible to provide a new property to allow it to respect `JAVA_HOME` while keeping backward-compatibility by default?

**Pull request closed without merging**
