### PR TITLE
Expose secure-random-algorithm configuration property

### PR DESCRIPTION
**Pull request by arhimondr**
Expose secure-random-algorithm configuration property for both, http client and http server.

On Linux (Unix) based operation systems `NativePRNG` algorithm is being used. This algorithm
fetched random bytes directly from the operation system using the `/dev/random` and `/dev/urandom`
files. It uses `/dev/random` to get the seed, and `/dev/urandom` to get the bytes.

The problem is that `/dev/urandom` is still slow, and single threaded.

Below is the test on the machine with 4 CPU

```
for i in {1..}; do dd if=/dev/urandom of=/dev/null bs=8K count=3000 & done

3000+0 records in
3000+0 records out
24576000 bytes (25 MB, 23 MiB) copied, 1,81277 s, 8,9 MB/s
```

```
for i in {1..4}; do dd if=/dev/urandom of=/dev/null bs=8K count=3000 & done

3000+0 records in
3000+0 records out
24576000 bytes (25 MB, 23 MiB) copied, 6,39533 s, 2.2 MB/s
3000+0 records in
3000+0 records out
24576000 bytes (25 MB, 23 MiB) copied, 6,49464 s, 2,2 MB/s
3000+0 records in
3000+0 records out
24576000 bytes (25 MB, 23 MiB) copied, 6,55815 s, 2,3 MB/s
3000+0 records in
3000+0 records out
24576000 bytes (25 MB, 23 MiB) copied, 6,60145 s, 2,1 MB/s
```

HTTPS (TLS) with block encryption requires ~16 bytes of random data for every single
encrypted block which is ~16kb of size. When the network is fast (infini-band) than
given throughput of `/dev/urandom` could be a bottle neck. For such cases it is better
to have a way how to switch the random number generator to something less strict, but
still secure. e.g.: java based `SHA1PRNG` generator that takes seed from the system,
but uses it's own long enough sequence to generate random bytes.

### CODE REVIEW

**Comment by johngmyers** [comment]
Note that SHA1PRNG will use /dev/random even though its source file is set to /dev/urandom. To use /dev/urandom one has to configure its source as something like /dev/./urandom

Also note that `SecureRandom.nextBytes(byte[])` is synchronized, independently of the provider implementation.

**Comment by electrum** [comment]
I don't think we should expose the exact algorithm name as a string. Instead, we should have boolean option to switch between the two types.

What is should be called and what the default should be is not immediately clear. If `SHA1PRNG` is faster, why not make it the default? Or skip the config and always use it? It is apparently the default on Windows. This post goes into detail: https://tersesystems.com/2015/12/17/the-right-way-to-use-securerandom/

**Comment by electrum** [comment]
Is it possible to write an HTTP client/server benchmark that demonstrates the difference between the two?

**Comment by arhimondr** [comment]
> Note that SHA1PRNG will use /dev/random 

It uses `/dev/random` only to generate seed. So, i think it is fine.

>  Instead, we should have boolean option to switch between the two types.

How would you call it? `http-client.ssl.use-pseudo-random`? `http-client.ssl.use-fast-secure-random`?

> If SHA1PRNG is faster, why not make it the default? 

It is pseudo random. But the sequence is pretty long though. It can be considered secure. But `/dev/random` is more reliable. I'm not a security addict actually, so in general i like your idea =)

> Is it possible to write an HTTP client/server benchmark that demonstrates the difference between the two?

Will do

**Comment by arhimondr** [comment]
Data transfer benchmark:

Environment:

- 32x vCPU Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
- 40gb/s infiniband network


No encryption:
```

Concurrency: 1

[Thread #0] Throughput: 1946282kb/s. Transferred: 116776960kb
[Total] Throughput: 1946282kb/s. Transferred: 116776960kb

Concurrency: 20

[Thread #0] Throughput: 229802kb/s. Transferred: 13788160kb
[Thread #1] Throughput: 231850kb/s. Transferred: 13911040kb
[Thread #2] Throughput: 231082kb/s. Transferred: 13864960kb
[Thread #3] Throughput: 232533kb/s. Transferred: 13952000kb
[Thread #4] Throughput: 231424kb/s. Transferred: 13885440kb
[Thread #5] Throughput: 230741kb/s. Transferred: 13844480kb
[Thread #6] Throughput: 234240kb/s. Transferred: 14054400kb
[Thread #7] Throughput: 227157kb/s. Transferred: 13629440kb
[Thread #8] Throughput: 233130kb/s. Transferred: 13987840kb
[Thread #9] Throughput: 233216kb/s. Transferred: 13992960kb
[Thread #10] Throughput: 233557kb/s. Transferred: 14013440kb
[Thread #11] Throughput: 232021kb/s. Transferred: 13921280kb
[Thread #12] Throughput: 232704kb/s. Transferred: 13962240kb
[Thread #13] Throughput: 233130kb/s. Transferred: 13987840kb
[Thread #14] Throughput: 232277kb/s. Transferred: 13936640kb
[Thread #15] Throughput: 232533kb/s. Transferred: 13952000kb
[Thread #16] Throughput: 234496kb/s. Transferred: 14069760kb
[Thread #17] Throughput: 232277kb/s. Transferred: 13936640kb
[Thread #18] Throughput: 231765kb/s. Transferred: 13905920kb
[Thread #19] Throughput: 236800kb/s. Transferred: 14208000kb
[Total] Throughput: 4646741kb/s. Transferred: 278804480kb
```

TLS. NativePRNG.
```
Concurrency: 1

[Thread #0] Throughput: 72192kb/s. Transferred: 4331520kb
[Total] Throughput: 72192kb/s. Transferred: 4331520kb

Concurrency: 20

[Thread #0] Throughput: 33792kb/s. Transferred: 2027520kb
[Thread #1] Throughput: 33450kb/s. Transferred: 2007040kb
[Thread #2] Throughput: 33621kb/s. Transferred: 2017280kb
[Thread #3] Throughput: 33024kb/s. Transferred: 1981440kb
[Thread #4] Throughput: 33365kb/s. Transferred: 2001920kb
[Thread #5] Throughput: 33024kb/s. Transferred: 1981440kb
[Thread #6] Throughput: 33365kb/s. Transferred: 2001920kb
[Thread #7] Throughput: 33280kb/s. Transferred: 1996800kb
[Thread #8] Throughput: 33280kb/s. Transferred: 1996800kb
[Thread #9] Throughput: 33194kb/s. Transferred: 1991680kb
[Thread #10] Throughput: 33109kb/s. Transferred: 1986560kb
[Thread #11] Throughput: 33194kb/s. Transferred: 1991680kb
[Thread #12] Throughput: 33450kb/s. Transferred: 2007040kb
[Thread #13] Throughput: 33280kb/s. Transferred: 1996800kb
[Thread #14] Throughput: 33365kb/s. Transferred: 2001920kb
[Thread #15] Throughput: 33450kb/s. Transferred: 2007040kb
[Thread #16] Throughput: 33706kb/s. Transferred: 2022400kb
[Thread #17] Throughput: 33450kb/s. Transferred: 2007040kb
[Thread #18] Throughput: 33621kb/s. Transferred: 2017280kb
[Thread #19] Throughput: 33536kb/s. Transferred: 2012160kb
[Total] Throughput: 667562kb/s. Transferred: 40053760kb
```

TLS. SHA1PRNG.
```
Concurrency: 1

[Thread #0] Throughput: 75776kb/s. Transferred: 4546560kb
[Total] Throughput: 75776kb/s. Transferred: 4546560kb

Concurrency: 20

[Thread #0] Throughput: 51370kb/s. Transferred: 3082240kb
[Thread #1] Throughput: 51797kb/s. Transferred: 3107840kb
[Thread #2] Throughput: 51285kb/s. Transferred: 3077120kb
[Thread #3] Throughput: 51882kb/s. Transferred: 3112960kb
[Thread #4] Throughput: 51370kb/s. Transferred: 3082240kb
[Thread #5] Throughput: 52394kb/s. Transferred: 3143680kb
[Thread #6] Throughput: 51285kb/s. Transferred: 3077120kb
[Thread #7] Throughput: 52309kb/s. Transferred: 3138560kb
[Thread #8] Throughput: 51797kb/s. Transferred: 3107840kb
[Thread #9] Throughput: 52480kb/s. Transferred: 3148800kb
[Thread #10] Throughput: 52736kb/s. Transferred: 3164160kb
[Thread #11] Throughput: 52565kb/s. Transferred: 3153920kb
[Thread #12] Throughput: 50517kb/s. Transferred: 3031040kb
[Thread #13] Throughput: 52821kb/s. Transferred: 3169280kb
[Thread #14] Throughput: 51114kb/s. Transferred: 3066880kb
[Thread #15] Throughput: 52138kb/s. Transferred: 3128320kb
[Thread #16] Throughput: 50858kb/s. Transferred: 3051520kb
[Thread #17] Throughput: 51370kb/s. Transferred: 3082240kb
[Thread #18] Throughput: 51541kb/s. Transferred: 3092480kb
[Thread #19] Throughput: 52650kb/s. Transferred: 3159040kb
[Total] Throughput: 1036288kb/s. Transferred: 62177280kb
```

Benchmark source:
- https://github.com/arhimondr/airlift/blob/secure_random_benchmark/sample-server/src/main/java/io/airlift/sample/HttpsServer.java
- https://github.com/arhimondr/airlift/blob/secure_random_benchmark/sample-server/src/main/java/io/airlift/sample/HttpsClient.java

**Comment by arhimondr** [comment]
Random number generator benchmark:

Environment:

- 32x vCPU Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz

```
[NativePRNG:Singleton] Concurrency: 1, Duration: 30.00s
[Thread #0] Throughput: 1568kb/s. Generated: 47069kb
[Total] Throughput: 1568kb/s. Generated: 47069kb

[NativePRNG:Singleton] Concurrency: 4, Duration: 30.00s
[Thread #0] Throughput: 397kb/s. Generated: 11939kb
[Thread #1] Throughput: 200kb/s. Generated: 6027kb
[Thread #2] Throughput: 570kb/s. Generated: 17100kb
[Thread #3] Throughput: 259kb/s. Generated: 7797kb
[Total] Throughput: 1428kb/s. Generated: 42863kb

[NativePRNG:Singleton] Concurrency: 24, Duration: 30.00s
[Thread #0] Throughput: 30kb/s. Generated: 904kb
[Thread #1] Throughput: 63kb/s. Generated: 1903kb
[Thread #2] Throughput: 54kb/s. Generated: 1623kb
[Thread #3] Throughput: 35kb/s. Generated: 1075kb
[Thread #4] Throughput: 34kb/s. Generated: 1031kb
[Thread #5] Throughput: 105kb/s. Generated: 3151kb
[Thread #6] Throughput: 88kb/s. Generated: 2646kb
[Thread #7] Throughput: 73kb/s. Generated: 2199kb
[Thread #8] Throughput: 62kb/s. Generated: 1867kb
[Thread #9] Throughput: 41kb/s. Generated: 1233kb
[Thread #10] Throughput: 56kb/s. Generated: 1695kb
[Thread #11] Throughput: 112kb/s. Generated: 3367kb
[Thread #12] Throughput: 49kb/s. Generated: 1475kb
[Thread #13] Throughput: 66kb/s. Generated: 1989kb
[Thread #14] Throughput: 52kb/s. Generated: 1587kb
[Thread #15] Throughput: 90kb/s. Generated: 2711kb
[Thread #16] Throughput: 128kb/s. Generated: 3843kb
[Thread #17] Throughput: 85kb/s. Generated: 2569kb
[Thread #18] Throughput: 31kb/s. Generated: 938kb
[Thread #19] Throughput: 45kb/s. Generated: 1355kb
[Thread #20] Throughput: 35kb/s. Generated: 1077kb
[Thread #21] Throughput: 29kb/s. Generated: 897kb
[Thread #22] Throughput: 17kb/s. Generated: 521kb
[Thread #23] Throughput: 43kb/s. Generated: 1317kb
[Total] Throughput: 1432kb/s. Generated: 42973kb

[NativePRNG:ThreadLocal] Concurrency: 4, Duration: 30.00s
[Thread #0] Throughput: 585kb/s. Generated: 17574kb
[Thread #1] Throughput: 299kb/s. Generated: 8983kb
[Thread #2] Throughput: 186kb/s. Generated: 5601kb
[Thread #3] Throughput: 358kb/s. Generated: 10768kb
[Total] Throughput: 1430kb/s. Generated: 42926kb

[NativePRNG:ThreadLocal] Concurrency: 24, Duration: 30.00s
[Thread #0] Throughput: 13kb/s. Generated: 408kb
[Thread #1] Throughput: 77kb/s. Generated: 2325kb
[Thread #2] Throughput: 19kb/s. Generated: 584kb
[Thread #3] Throughput: 60kb/s. Generated: 1828kb
[Thread #4] Throughput: 63kb/s. Generated: 1894kb
[Thread #5] Throughput: 80kb/s. Generated: 2420kb
[Thread #6] Throughput: 61kb/s. Generated: 1835kb
[Thread #7] Throughput: 78kb/s. Generated: 2356kb
[Thread #8] Throughput: 5kb/s. Generated: 168kb
[Thread #9] Throughput: 69kb/s. Generated: 2098kb
[Thread #10] Throughput: 120kb/s. Generated: 3609kb
[Thread #11] Throughput: 43kb/s. Generated: 1311kb
[Thread #12] Throughput: 120kb/s. Generated: 3621kb
[Thread #13] Throughput: 95kb/s. Generated: 2864kb
[Thread #14] Throughput: 122kb/s. Generated: 3675kb
[Thread #15] Throughput: 14kb/s. Generated: 435kb
[Thread #16] Throughput: 27kb/s. Generated: 822kb
[Thread #17] Throughput: 99kb/s. Generated: 2975kb
[Thread #18] Throughput: 70kb/s. Generated: 2105kb
[Thread #19] Throughput: 70kb/s. Generated: 2118kb
[Thread #20] Throughput: 63kb/s. Generated: 1911kb
[Thread #21] Throughput: 10kb/s. Generated: 329kb
[Thread #22] Throughput: 8kb/s. Generated: 266kb
[Thread #23] Throughput: 40kb/s. Generated: 1217kb
[Total] Throughput: 1439kb/s. Generated: 43174kb

[SHA1PRNG:Singleton] Concurrency: 1, Duration: 30.00s
[Thread #0] Throughput: 36949kb/s. Generated: 1108475kb
[Total] Throughput: 36949kb/s. Generated: 1108475kb

[SHA1PRNG:Singleton] Concurrency: 4, Duration: 30.00s
[Thread #0] Throughput: 5257kb/s. Generated: 157731kb
[Thread #1] Throughput: 5320kb/s. Generated: 159605kb
[Thread #2] Throughput: 7614kb/s. Generated: 228426kb
[Thread #3] Throughput: 5974kb/s. Generated: 179241kb
[Total] Throughput: 24166kb/s. Generated: 725003kb

[SHA1PRNG:Singleton] Concurrency: 24, Duration: 30.00s
[Thread #0] Throughput: 712kb/s. Generated: 21364kb
[Thread #1] Throughput: 1022kb/s. Generated: 30668kb
[Thread #2] Throughput: 1069kb/s. Generated: 32092kb
[Thread #3] Throughput: 1315kb/s. Generated: 39468kb
[Thread #4] Throughput: 1093kb/s. Generated: 32797kb
[Thread #5] Throughput: 890kb/s. Generated: 26720kb
[Thread #6] Throughput: 1169kb/s. Generated: 35078kb
[Thread #7] Throughput: 710kb/s. Generated: 21305kb
[Thread #8] Throughput: 1124kb/s. Generated: 33742kb
[Thread #9] Throughput: 1093kb/s. Generated: 32816kb
[Thread #10] Throughput: 851kb/s. Generated: 25544kb
[Thread #11] Throughput: 1097kb/s. Generated: 32934kb
[Thread #12] Throughput: 1292kb/s. Generated: 38761kb
[Thread #13] Throughput: 596kb/s. Generated: 17881kb
[Thread #14] Throughput: 1305kb/s. Generated: 39162kb
[Thread #15] Throughput: 1341kb/s. Generated: 40247kb
[Thread #16] Throughput: 628kb/s. Generated: 18868kb
[Thread #17] Throughput: 1197kb/s. Generated: 35922kb
[Thread #18] Throughput: 896kb/s. Generated: 26900kb
[Thread #19] Throughput: 380kb/s. Generated: 11422kb
[Thread #20] Throughput: 1101kb/s. Generated: 33030kb
[Thread #21] Throughput: 1189kb/s. Generated: 35687kb
[Thread #22] Throughput: 883kb/s. Generated: 26505kb
[Thread #23] Throughput: 867kb/s. Generated: 26036kb
[Total] Throughput: 23831kb/s. Generated: 714949kb

[SHA1PRNG:ThreadLocal] Concurrency: 4, Duration: 30.00s
[Thread #0] Throughput: 38310kb/s. Generated: 1149309kb
[Thread #1] Throughput: 25204kb/s. Generated: 756137kb
[Thread #2] Throughput: 33391kb/s. Generated: 1001741kb
[Thread #3] Throughput: 33989kb/s. Generated: 1019693kb
[Total] Throughput: 130896kb/s. Generated: 3926880kb

[SHA1PRNG:ThreadLocal] Concurrency: 24, Duration: 30.00s
[Thread #0] Throughput: 10035kb/s. Generated: 301056kb
[Thread #1] Throughput: 10315kb/s. Generated: 309451kb
[Thread #2] Throughput: 20134kb/s. Generated: 604022kb
[Thread #3] Throughput: 18994kb/s. Generated: 569821kb
[Thread #4] Throughput: 22358kb/s. Generated: 670764kb
[Thread #5] Throughput: 15027kb/s. Generated: 450823kb
[Thread #6] Throughput: 22875kb/s. Generated: 686252kb
[Thread #7] Throughput: 15487kb/s. Generated: 464613kb
[Thread #8] Throughput: 20255kb/s. Generated: 607667kb
[Thread #9] Throughput: 15681kb/s. Generated: 470449kb
[Thread #10] Throughput: 16378kb/s. Generated: 491366kb
[Thread #11] Throughput: 27962kb/s. Generated: 838885kb
[Thread #12] Throughput: 11420kb/s. Generated: 342620kb
[Thread #13] Throughput: 12781kb/s. Generated: 383446kb
[Thread #14] Throughput: 13552kb/s. Generated: 406576kb
[Thread #15] Throughput: 14862kb/s. Generated: 445885kb
[Thread #16] Throughput: 15105kb/s. Generated: 453157kb
[Thread #17] Throughput: 13306kb/s. Generated: 399207kb
[Thread #18] Throughput: 18321kb/s. Generated: 549630kb
[Thread #19] Throughput: 20721kb/s. Generated: 621630kb
[Thread #20] Throughput: 13509kb/s. Generated: 405291kb
[Thread #21] Throughput: 16756kb/s. Generated: 502706kb
[Thread #22] Throughput: 19291kb/s. Generated: 578735kb
[Thread #23] Throughput: 22395kb/s. Generated: 671875kb
[Total] Throughput: 407530kb/s. Generated: 12225927kb
```

**Comment by electrum** [comment]
I'm not sure how to name it, since I don't fully understand the tradeoffs. If we call it `use-fast`, why would you not want to be fast? Or we can say `use-fast-but-possibly-insecure` or `use-slower-but-maybe-more-secure`, but those are bad names, too.

Note that JMH is much better for doing this sort of benchmark. However, I don't really care about `SecureRandom` performance in isolation. What matters is that when running an HTTP server and client, what is the performance impact of different `SecureRandom` implementations? I'm surprised that it could make a difference at all (considering all the other work that needs to be done).

**Comment by arhimondr** [comment]
@electrum Based on the data transfer benchmark data transfer is only 2 times slower with using `NativePRNG`. 

But what i'm experiencing on a real presto cluster running simple aggregation query is much worse.

I ran  `SELECT suppkey, count(*) AS c FROM "lineitem" GROUP BY suppkey ORDER BY c DESC LIMIT 10;` on `1tb` TPCH data source on 8 nodes Presto cluster. 

With insecure internal trasfer it takes ~ 1m 20s.  With HTTPS enabled it takes ~4m. 

Diving deeper into investigation i found that  `java.security.SecureRandom.nextBytes(byte[])` is the hot spot. And lot of threads are blocked at this method. Besides the SSL encryption code, a lot of invocation are coming from `java.util.UUID.randomUUID()`, which is being called from `TraceTokenFilter` and `ServiceAnouncment`. So the native `SecureRandom` is overloaded. 

selection_023

Once i switched PRNG algorithm to SHA1PRNG, the query takes only ~2m, and all the cores became utilized much better.

**Comment by electrum** [comment]
This should fix the `ServiceDescriptorBuilder` issue: https://github.com/airlift/airlift/pull/485

**Comment by arhimondr** [comment]
@electrum 

> I'm not sure how to name it, since I don't fully understand the tradeoffs. If we call it use-fast, why would you not want to be fast? Or we can say use-fast-but-possibly-insecure or use-slower-but-maybe-more-secure, but those are bad names, too.

Such names might be really confusing. I decided to just set the `SHA1PRNG` as a default. And hopefully no one would ever want to change it. But still, i think it is better to leave such ability.

> Note that JMH is much better for doing this sort of benchmark. However, I don't really care about SecureRandom performance in isolation

I know that JMH is better. But i aggree that SecureRandom performance in isolation doesn't matter a lot. So i just wanted to see the rough estimates of how fast it is.

> What matters is that when running an HTTP server and client, what is the performance impact of different SecureRandom implementations?

Please check the first benchmark. It is most important part. Then please check the profiler screen-shot. Native SecureRandom is operation system wide singleton. And it is really slow. So, it is easy to overload it.

**Comment by electrum** [comment]
This fixes trace tokens: https://github.com/airlift/airlift/pull/486

**Comment by arhimondr** [comment]
@electrum Thanks for fixing this. But still, i believe it is worth to change the RNG algorithm for Http Server/Client. It is twice as faster for high concurrency.

**Comment by martint** [comment]
We're going to merge this as is. Can you take a look the build failures?

**Comment by arhimondr** [comment]
@martint It was some intermittent failure. Now tests pass.

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
