### PR TITLE
Bump byte-buddy from 1.10.22 to 1.12.6

### PR DESCRIPTION
**Pull request by findinpath**

### CODE REVIEW

**Comment by findepi** [comment]
add note in CHANGES

what is the reason for the change?

**Comment by findepi** [comment]
> what is the reason for the change?

per offline discussion, this is to aid migrating Trino to Java 17
cc @wendigo

**Comment by wendigo** [comment]
@findepi use same version in both airlift and tempto which are dependencies of Trino (conflicting now) and support JDK 17

**Comment by findinpath** [comment]
@wendigo  FYI tempto is currently using `byte-buddy` version `1.12.6`

**Pull request merged**
